'output_dir': './model/transformer2'
'max_length': 20
'batch_size': 32
'num_epochs': 50
'lr': 0.001
'proj_share_weight': true
'd_k': 32
'd_v': 32
'd_model': 200
'd_word_vec': 200
'd_inner_hid': 256
'n_layers': 3
'n_head': 6
'dropout': 0.2
'src_word_vec': "../data/common/en/glove_200d"
